apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "my-app-secret"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - key: API_KEY
          objectName: "my-app-secret"
