apiVersion: v2
name: simple-web-app
description: A simple web application
version: 0.1.0
appVersion: "1.0"

// helm/app/values.yaml
replicaCount: 2
image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
