# Prometheus & Grafana combined values for kube-prometheus-stack
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 7d
    scrapeInterval: 15s

grafana:
  adminPassword: prom-operator
  service:
    type: LoadBalancer
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.local

kube-state-metrics:
  enabled: true

# How to install:
# helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# helm repo update
# helm install monitoring prometheus-community/kube-prometheus-stack -f helm/monitoring/prometheus-grafana-values.yaml
